version: '3.8'

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: Nestjs
    ports:
      - 4000:4000
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=knk
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./mongo_data:/data/db

networks:
  app-network:
    driver: bridge
