version: '3.8'

services:
  nestjs:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    container_name: nestjs-BE
    environment:
      - SUFFIX_ENV_NAME=dev
    ports:
      - ${PORT}:${PORT}
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./:/usr/src/app
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MONGO_INITDB_DATABASE=${DATABASE_NAME}
    ports:
      - "27017:27017"
    restart: unless-stopped
    networks:
      - app-network
    volumes:
      - ./mongo_data:/data/db

networks:
  app-network:
    driver: bridge
