version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    environment:
      - MONGO_INITDB_DATABASE=knk
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - ./mongo_data:/data/db
