name: "Deploy to Google Cloud Run"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secret.GCE_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/${{ secret.GCE_PROJECT }}/knk:latest
          build-args: |
            HTTP_PORT=8080

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: gcr.io/${{ secret.GCE_PROJECT }}/knk:latest
          service: 'knk'
          region: 'asia-southeast1-b'
          platform: managed
          allow-unauthenticated: true
          env_vars: |
              PORT=80
              
      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
