name: "Deploy to Google Cloud Run"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.GCE_PROJECT }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCE_SA_KEY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: export service account to file
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS" > ./firebase-admin.json

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCE_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: Configure docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: gcr.io/knnk-159c7/knk:latest
          build-args: |
            HTTP_PORT=80

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@main
        with:
          image: gcr.io/knnk-159c7/knk:latest
          service: 'knk'
          region: 'asia-southeast1-b'
          platform: managed
          allow-unauthenticated: true
          env_vars: |
              PORT=80
              
      - name: 'Use output'
        run: 'curl "${{ steps.deploy.outputs.url }}"'
